# Site settings
title: Lauritz' blog
email: mail@lauritz.me
description: > # this means to ignore newlines until "baseurl:"
  From novice to expert
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.lauritz.me" # the base hostname & protocol for your site
twitter_username: lauritzsh
github_username:  lauritzsh

# Build settings
markdown: redcarpet
